# Generated by Django 5.0.2 on 2024-03-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactmessage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminreply',
            name='message',
        ),
        migrations.AddField(
            model_name='adminreply',
            name='adminmessage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='contactmessage.contactmessage'),
        ),
        migrations.AlterField(
            model_name='adminreply',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
