# Generated by Django 5.0.2 on 2024-03-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactmessage', '0002_remove_adminreply_message_adminreply_adminmessage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminreply',
            old_name='adminmessage',
            new_name='message',
        ),
    ]
